In [62]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [63]:
df=pd.read_csv('iris.data.csv',header=None)

In [64]:
df.columns=['sepal_length','sepal_width','petal_length','petal_width','species']

In [65]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [66]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['species']=encoder.fit_transform(df['species'])

In [67]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [68]:
df=df.drop(columns=['petal_length','petal_width'])

In [69]:
df[df['species']!=0]

     sepal_length  sepal_width  species
50            7.0          3.2        1
51            6.4          3.2        1
52            6.9          3.1        1
53            5.5          2.3        1
54            6.5          2.8        1
..            ...          ...      ...
145           6.7          3.0        2
146           6.3          2.5        2
147           6.5          3.0        2
148           6.2          3.4        2
149           5.9          3.0        2

[100 rows x 3 columns]

In [70]:
X=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [71]:
clf1=LogisticRegression()
clf2=RandomForestClassifier()
clf3=KNeighborsClassifier()
from sklearn.model_selection import cross_val_score

In [72]:
estimators=[('lr',clf1),('rf',clf2),('kn',clf3)]

In [73]:
for estimator in estimators:
    score=cross_val_score(estimator[1],X,y,cv=10,scoring='accuracy')
    print(estimator[0],score.mean())

lr 0.8066666666666669
rf 0.72
kn 0.76

In [74]:
# hardVoting:
from sklearn.ensemble import VotingClassifier
vc=VotingClassifier(estimators=estimators)
score=cross_val_score(vc,X,y,cv=10,scoring='accuracy')
print(score.mean())

0.7733333333333333

In [75]:
#softvoting
vc=VotingClassifier(estimators=estimators,voting='soft')
score=cross_val_score(vc,X,y,cv=10,scoring='accuracy')
print(score.mean())

0.7733333333333333

In [78]:
#weighted voting(assign weights to each base model)
for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            vc=VotingClassifier(estimators=estimators,weights=[i,j,k])
            score=cross_val_score(vc,X,y,cv=10,scoring='accuracy')
            print('i',i,'j',j,'k',k,score.mean())

i 1 j 1 k 1 0.7733333333333333
i 1 j 1 k 2 0.76
i 1 j 1 k 3 0.76
i 1 j 2 k 1 0.7466666666666667
i 1 j 2 k 2 0.7733333333333333
i 1 j 2 k 3 0.76
i 1 j 3 k 1 0.7266666666666667
i 1 j 3 k 2 0.7533333333333333
i 1 j 3 k 3 0.7666666666666666
i 2 j 1 k 1 0.7866666666666667
i 2 j 1 k 2 0.7733333333333333
i 2 j 1 k 3 0.76
i 2 j 2 k 1 0.7733333333333333
i 2 j 2 k 2 0.7733333333333333
i 2 j 2 k 3 0.78
i 2 j 3 k 1 0.74
i 2 j 3 k 2 0.7733333333333333
i 2 j 3 k 3 0.7666666666666666
i 3 j 1 k 1 0.8066666666666669
i 3 j 1 k 2 0.78
i 3 j 1 k 3 0.7666666666666666
i 3 j 2 k 1 0.7866666666666667
i 3 j 2 k 2 0.7733333333333333
i 3 j 2 k 3 0.7733333333333333
i 3 j 3 k 1 0.7733333333333333
i 3 j 3 k 2 0.7733333333333333
i 3 j 3 k 3 0.7733333333333333